-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_generations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_id uuid,
  generation_type text NOT NULL CHECK (generation_type = ANY (ARRAY['idea'::text, 'script'::text, 'caption'::text, 'hashtags'::text, 'title'::text, 'brief'::text])),
  prompt text NOT NULL,
  input_context jsonb,
  output text NOT NULL,
  model text,
  tokens_used integer,
  was_accepted boolean DEFAULT false,
  generated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_generations_pkey PRIMARY KEY (id),
  CONSTRAINT ai_generations_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id),
  CONSTRAINT ai_generations_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_brand_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  audit_run_id uuid NOT NULL,
  executive_summary jsonb,
  overall_score integer CHECK (overall_score >= 0 AND overall_score <= 100),
  brand_clarity jsonb,
  strategic_focus_areas jsonb,
  solutions jsonb,
  inspiration_guidance jsonb,
  next_30_day_focus jsonb,
  platforms jsonb,
  content_patterns jsonb,
  platform_priority_order jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_brand_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT audit_brand_reviews_audit_run_id_fkey FOREIGN KEY (audit_run_id) REFERENCES public.audit_runs(id)
);
CREATE TABLE public.audit_platform_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  audit_run_id uuid NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['instagram'::text, 'tiktok'::text, 'youtube'::text, 'twitter'::text, 'linkedin'::text, 'website'::text])),
  profile jsonb,
  metrics jsonb,
  hook_analysis jsonb,
  post_count integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_platform_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT audit_platform_snapshots_audit_run_id_fkey FOREIGN KEY (audit_run_id) REFERENCES public.audit_runs(id)
);
CREATE TABLE public.audit_raw_platform_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  audit_run_id uuid NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['instagram'::text, 'tiktok'::text, 'youtube'::text, 'twitter'::text, 'linkedin'::text, 'website'::text])),
  raw_payload jsonb NOT NULL,
  scraped_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_raw_platform_data_pkey PRIMARY KEY (id),
  CONSTRAINT audit_raw_platform_data_audit_run_id_fkey FOREIGN KEY (audit_run_id) REFERENCES public.audit_runs(id)
);
CREATE TABLE public.audit_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  audit_signup_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'in_progress'::text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  report_url text,
  delivered_at timestamp without time zone,
  review_url text,
  CONSTRAINT audit_runs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_runs_audit_signup_id_fkey FOREIGN KEY (audit_signup_id) REFERENCES public.audit_signups(id)
);
CREATE TABLE public.audit_signups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  company_name text,
  social_handles jsonb,
  status text NOT NULL DEFAULT 'pending'::text,
  assigned_to uuid,
  notes text,
  stripe_payment_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  converted_to_client_id uuid,
  CONSTRAINT audit_signups_pkey PRIMARY KEY (id),
  CONSTRAINT audit_signups_converted_to_client_id_fkey FOREIGN KEY (converted_to_client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.brand_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid,
  audit_signup_id uuid,
  brand_name text NOT NULL,
  tagline text,
  description text,
  brand_voice jsonb DEFAULT '{"dos": [], "tone": [], "donts": [], "personality": [], "example_phrases": []}'::jsonb,
  target_audience jsonb DEFAULT '[{"name": "", "goals": [], "platforms": [], "pain_points": [], "demographics": ""}]'::jsonb,
  keywords jsonb DEFAULT '[]'::jsonb,
  content_pillars jsonb DEFAULT '[]'::jsonb,
  colors jsonb DEFAULT '{"accent": "", "primary": "", "secondary": ""}'::jsonb,
  fonts jsonb DEFAULT '{"body": "", "heading": ""}'::jsonb,
  logo_url text,
  brand_assets_folder text,
  competitors jsonb DEFAULT '[]'::jsonb,
  inspiration_accounts jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT brand_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT brand_profiles_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT brand_profiles_audit_signup_id_fkey FOREIGN KEY (audit_signup_id) REFERENCES public.audit_signups(id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  email text NOT NULL,
  company_name text,
  phone text,
  avatar_url text,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_number integer NOT NULL DEFAULT nextval('content_content_number_seq'::regclass),
  title text NOT NULL,
  description text,
  content_type_id uuid,
  client_id uuid,
  brand_id uuid,
  brief text,
  idea_notes text,
  ai_suggestions jsonb,
  script text,
  caption text,
  hashtags ARRAY DEFAULT '{}'::text[],
  cta text,
  media jsonb DEFAULT '[]'::jsonb,
  thumbnail_url text,
  raw_assets jsonb DEFAULT '[]'::jsonb,
  final_assets jsonb DEFAULT '[]'::jsonb,
  status text DEFAULT 'inbox'::text CHECK (status = ANY (ARRAY['inbox'::text, 'ideation'::text, 'creating'::text, 'review'::text, 'revision'::text, 'approved'::text, 'scheduled'::text, 'published'::text])),
  created_by uuid,
  assigned_to uuid,
  assigned_editor uuid,
  assigned_designer uuid,
  due_date date,
  scheduled_at timestamp with time zone,
  published_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  revision_count integer DEFAULT 0,
  publish_url text,
  platform_post_id text,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  tags ARRAY DEFAULT '{}'::text[],
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_pkey PRIMARY KEY (id),
  CONSTRAINT content_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.content_types(id),
  CONSTRAINT content_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT content_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brand_profiles(id),
  CONSTRAINT content_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT content_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT content_assigned_editor_fkey FOREIGN KEY (assigned_editor) REFERENCES auth.users(id),
  CONSTRAINT content_assigned_designer_fkey FOREIGN KEY (assigned_designer) REFERENCES auth.users(id),
  CONSTRAINT content_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.content_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_id uuid NOT NULL,
  user_id uuid NOT NULL,
  comment text NOT NULL,
  media_reference jsonb,
  parent_id uuid,
  is_resolved boolean DEFAULT false,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  is_approval_action boolean DEFAULT false,
  approval_decision text CHECK (approval_decision = ANY (ARRAY['approved'::text, 'revision_requested'::text, 'rejected'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_comments_pkey PRIMARY KEY (id),
  CONSTRAINT content_comments_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id),
  CONSTRAINT content_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT content_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.content_comments(id),
  CONSTRAINT content_comments_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.content_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  client_id uuid,
  title text NOT NULL,
  content text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'review'::text, 'approved'::text, 'scheduled'::text, 'published'::text, 'rejected'::text])),
  platform text CHECK (platform = ANY (ARRAY['instagram'::text, 'tiktok'::text, 'youtube'::text, 'twitter'::text, 'linkedin'::text, 'facebook'::text])),
  scheduled_at timestamp with time zone,
  published_at timestamp with time zone,
  media_urls ARRAY,
  hashtags ARRAY,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT content_posts_pkey PRIMARY KEY (id),
  CONSTRAINT content_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT content_posts_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id)
);
CREATE TABLE public.content_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  content_type_id uuid,
  reference_urls ARRAY DEFAULT '{}'::text[],
  attachments jsonb DEFAULT '[]'::jsonb,
  requested_date date,
  urgency text DEFAULT 'normal'::text CHECK (urgency = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'converted'::text])),
  converted_to_content_id uuid,
  admin_notes text,
  responded_by uuid,
  responded_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_requests_pkey PRIMARY KEY (id),
  CONSTRAINT content_requests_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT content_requests_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.content_types(id),
  CONSTRAINT content_requests_converted_to_content_id_fkey FOREIGN KEY (converted_to_content_id) REFERENCES public.content(id),
  CONSTRAINT content_requests_responded_by_fkey FOREIGN KEY (responded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.content_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  content_type_id uuid,
  template_brief text,
  template_script text,
  template_caption text,
  template_hashtags ARRAY DEFAULT '{}'::text[],
  ai_prompt text,
  is_global boolean DEFAULT false,
  client_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_templates_pkey PRIMARY KEY (id),
  CONSTRAINT content_templates_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES public.content_types(id),
  CONSTRAINT content_templates_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT content_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.content_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  icon text,
  color text,
  platform text,
  default_template jsonb DEFAULT '{"sections": ["brief", "script", "caption", "hashtags"]}'::jsonb,
  ai_prompts jsonb DEFAULT '{"script": "", "caption": "", "hashtags": "", "ideation": ""}'::jsonb,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.content_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_id uuid NOT NULL,
  version_number integer NOT NULL,
  snapshot jsonb NOT NULL,
  change_summary text,
  changed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_versions_pkey PRIMARY KEY (id),
  CONSTRAINT content_versions_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id),
  CONSTRAINT content_versions_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content(id)
);
CREATE TABLE public.creator_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  display_name text NOT NULL,
  bio text,
  specialty ARRAY DEFAULT '{}'::text[],
  skills ARRAY DEFAULT '{}'::text[],
  portfolio_url text,
  portfolio_samples jsonb DEFAULT '[]'::jsonb,
  is_available boolean DEFAULT true,
  hourly_rate numeric,
  total_projects integer DEFAULT 0,
  completed_projects integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT creator_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT creator_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  role USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::invitation_status,
  client_id uuid,
  creator_name text,
  creator_specialty text,
  invited_by uuid,
  message text,
  token text UNIQUE,
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  accepted_at timestamp with time zone,
  accepted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invitations_pkey PRIMARY KEY (id),
  CONSTRAINT invitations_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id),
  CONSTRAINT invitations_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  company_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  role text DEFAULT 'client'::text,
  department text,
  is_active boolean DEFAULT true,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  category text NOT NULL CHECK (category = ANY (ARRAY['ai_writing'::text, 'analytics'::text, 'media'::text])),
  icon text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tools_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'client'::app_role,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);